name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
  patch:
    labels:
      - "type: bug"
      - "type: maintenance"
      - "type: docs"
      - "type: dependencies"
      - "type: security"

template: |
  ## Changes

  $CHANGES
